"""
monologue_end -> _60_token_meter

Fires after every agent monologue (one full LLM call + tool execution cycle).
Extracts usage_metadata from the last AIMessage in history.

LangChain usage_metadata keys (provider-dependent):
  input_tokens                  tokens sent to model this call
  output_tokens                 tokens generated by model
  cache_read_input_tokens       input tokens served from provider cache
  cache_creation_input_tokens   tokens written into cache this call (Anthropic)

A0 architecture note:
  Every tool call resends the FULL conversation history as input.
  So input_tokens grows with each iteration. Cache tokens show how much
  of that repeated history was served from cache instead of re-processed.
  High cache_read / input ratio = cache is working and saving money.
"""
from __future__ import annotations
import os
import json
import time
from helpers.extension import Extension
from agent import LoopData

METER_DIR = os.path.join("work", "token_meter")


def _cfg(key: str, default):
    env_val = os.environ.get(f"TOKEN_METER_{key.upper()}")
    if env_val is not None:
        if isinstance(default, bool):
            return env_val.lower() in ("1", "true", "yes")
        if isinstance(default, float):
            try: return float(env_val)
            except: pass
        return env_val
    try:
        import yaml
        cfg_path = os.path.join(os.path.dirname(__file__), "..", "..", "..", "default_config.yaml")
        with open(os.path.abspath(cfg_path), "r") as f:
            data = yaml.safe_load(f) or {}
        v = data.get(key, default)
        if isinstance(default, float):
            return float(v)
        return v
    except Exception:
        return default


ENABLED           = _cfg("enabled",              True)
SHOW_PER_CALL     = _cfg("show_per_call",         True)
SHOW_SESSION      = _cfg("show_session_totals",   True)
WRITE_JSONL       = _cfg("write_jsonl",            True)
PRICE_IN          = float(_cfg("price_input_per_1m",       0.0))
PRICE_OUT         = float(_cfg("price_output_per_1m",      0.0))
PRICE_CACHE_READ  = float(_cfg("price_cache_read_per_1m",  0.0))
PRICE_CACHE_WRITE = float(_cfg("price_cache_write_per_1m", 0.0))


def _session_id(agent) -> str:
    try:
        sid = getattr(agent, "chat_id", None) or getattr(agent.context, "id", None)
        return str(sid)[:32] if sid else "default"
    except Exception:
        return "default"


def _model_name(agent) -> str:
    try:
        return str(agent.config.chat_model.name)
    except Exception:
        try:
            return str(agent.config.chat_model)
        except Exception:
            return "unknown"


def _extract_usage(agent) -> dict:
    """
    Walk history in reverse, find the last AIMessage with usage_metadata.
    Handles both LangChain message objects and plain dicts.
    """
    try:
        msgs = agent.history.output()
        for msg in reversed(msgs):
            # LangChain AIMessage object
            um = getattr(msg, "usage_metadata", None)
            if um and isinstance(um, dict) and "input_tokens" in um:
                return {
                    "input":       int(um.get("input_tokens", 0)),
                    "output":      int(um.get("output_tokens", 0)),
                    "cache_read":  int(um.get("cache_read_input_tokens", 0)),
                    "cache_write": int(um.get("cache_creation_input_tokens", 0)),
                }
            # Plain dict wrapper
            if isinstance(msg, dict):
                um = msg.get("usage_metadata") or msg.get("usage") or {}
                if um and "input_tokens" in um:
                    return {
                        "input":       int(um.get("input_tokens", 0)),
                        "output":      int(um.get("output_tokens", 0)),
                        "cache_read":  int(um.get("cache_read_input_tokens", 0)),
                        "cache_write": int(um.get("cache_creation_input_tokens", 0)),
                    }
    except Exception:
        pass
    return {"input": 0, "output": 0, "cache_read": 0, "cache_write": 0}


def _cost(inp: int, out: int, cr: int, cw: int) -> float:
    return (
        inp * PRICE_IN          / 1_000_000
        + out * PRICE_OUT        / 1_000_000
        + cr  * PRICE_CACHE_READ / 1_000_000
        + cw  * PRICE_CACHE_WRITE/ 1_000_000
    )


def _fmt_cost(usd: float) -> str:
    if PRICE_IN == 0.0 and PRICE_OUT == 0.0:
        return "$0 (set prices in default_config.yaml)"
    if usd < 0.0001:
        return f"${usd:.6f}"
    return f"${usd:.4f}"


def _cache_pct(inp: int, cr: int) -> str:
    if inp <= 0:
        return "n/a"
    return f"{100 * cr / inp:.1f}%"


def _get_totals(context) -> dict:
    return context.data.get("_token_meter_totals", {
        "input": 0, "output": 0, "cache_read": 0, "cache_write": 0,
        "cost": 0.0, "calls": 0,
    })


def _update_totals(context, usage: dict, call_cost: float) -> dict:
    t = _get_totals(context)
    t["input"]       += usage["input"]
    t["output"]      += usage["output"]
    t["cache_read"]  += usage["cache_read"]
    t["cache_write"] += usage["cache_write"]
    t["cost"]        += call_cost
    t["calls"]       += 1
    context.data["_token_meter_totals"] = t
    return t


def _append_jsonl(session_id: str, record: dict):
    try:
        os.makedirs(METER_DIR, exist_ok=True)
        path = os.path.join(METER_DIR, f"{session_id}.jsonl")
        with open(path, "a", encoding="utf-8") as f:
            f.write(json.dumps(record) + "\n")
    except Exception:
        pass


class TokenMeter(Extension):

    async def execute(self, loop_data: LoopData = LoopData(), **kwargs):
        if not ENABLED or not self.agent or self.agent.number != 0:
            return
        try:
            agent      = self.agent
            context    = agent.context
            session_id = _session_id(agent)
            model      = _model_name(agent)

            usage     = _extract_usage(agent)
            inp       = usage["input"]
            out       = usage["output"]
            cr        = usage["cache_read"]
            cw        = usage["cache_write"]
            call_cost = _cost(inp, out, cr, cw)
            totals    = _update_totals(context, usage, call_cost)

            # ── JSONL ─────────────────────────────────────────────────
            if WRITE_JSONL and (inp > 0 or out > 0):
                _append_jsonl(session_id, {
                    "ts":            time.time(),
                    "model":         model,
                    "session":       session_id,
                    "call":          totals["calls"],
                    "input":         inp,
                    "output":        out,
                    "cache_read":    cr,
                    "cache_write":   cw,
                    "cost_usd":      round(call_cost, 6),
                    "cache_hit_pct": round(100 * cr / inp, 2) if inp > 0 else 0,
                })

            # ── Per-call panel ─────────────────────────────────────────
            if SHOW_PER_CALL and (inp > 0 or out > 0):
                cache_lines = ""
                if cr > 0 or cw > 0:
                    cache_lines = (
                        f"  cache_read  : {cr:>10,}  ({_cache_pct(inp, cr)} of input)\n"
                        f"  cache_write : {cw:>10,}\n"
                    )
                warn = ""
                if cr == 0 and cw == 0 and inp > 0:
                    warn = "  ⚠️  No cache tokens — provider may not support caching\n"

                context.log.log(
                    type="hint",
                    heading=f"🪙 Token Meter — Call #{totals['calls']} ({model})",
                    content=(
                        f"  input       : {inp:>10,}\n"
                        f"  output      : {out:>10,}\n"
                        + cache_lines + warn
                        + f"  cost (call) : {_fmt_cost(call_cost)}\n"
                    ),
                )

            # ── Session totals panel ────────────────────────────────
            if SHOW_SESSION and totals["calls"] > 0:
                t_in  = totals["input"]
                t_out = totals["output"]
                t_cr  = totals["cache_read"]
                t_cw  = totals["cache_write"]

                cache_eff = ""
                if t_cr > 0 or t_cw > 0:
                    # savings = what cache_read would have cost at full input price vs cache price
                    savings = t_cr * (PRICE_IN - PRICE_CACHE_READ) / 1_000_000
                    cache_eff = (
                        f"  total cache_read  : {t_cr:>10,}  ({_cache_pct(t_in, t_cr)} of input)\n"
                        f"  total cache_write : {t_cw:>10,}\n"
                        f"  cache savings     : {_fmt_cost(savings)}\n"
                    )

                context.log.log(
                    type="hint",
                    heading=f"📊 Token Meter — Session Totals ({totals['calls']} calls)",
                    content=(
                        f"  total input       : {t_in:>10,}\n"
                        f"  total output      : {t_out:>10,}\n"
                        + cache_eff
                        + f"  total cost        : {_fmt_cost(totals['cost'])}\n"
                        + f"  avg input/call    : {t_in // max(1, totals['calls']):>10,}\n"
                    ),
                )

        except Exception as exc:
            try:
                self.agent.context.log.log(
                    type="hint",
                    heading="⚠️ Token Meter — Error",
                    content=str(exc),
                )
            except Exception:
                pass
